# Generated by Django 3.2.14 on 2023-02-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20230228_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
    ]
