# Generated by Django 3.2.14 on 2023-03-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='academic_years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.academicyear'),
        ),
    ]
