# Generated by Django 3.2.14 on 2024-02-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20240123_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
    ]
