# Generated by Django 3.2.14 on 2024-06-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_target'),
        ('post', '0008_post_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.target'),
        ),
    ]
