# Generated by Django 3.2.14 on 2026-09-05 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_faculty_registration_and_otp'),
        ('post', '0009_post_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='estimated_score',
            field=models.FloatField(blank=True, help_text="Computed at submission time from the category rule and the submitter's author share.", null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quartile',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='validated_score',
            field=models.FloatField(blank=True, help_text='Set by the reviewer at approval time; may differ from the estimate.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'На рассмотрении'), (2, 'Одобрено'), (3, 'Отклонено')], default=1),
        ),
        migrations.CreateModel(
            name='PostCoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_authors', to='post.post')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_author_requests', to='user.teacher')),
            ],
            options={
                'unique_together': {('post', 'teacher')},
            },
        ),
    ]
