# Generated by Django 3.2.14 on 2023-02-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_academicyear'),
        ('category', '0004_auto_20230228_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gt_150', models.IntegerField(blank=True, default=0, null=True)),
                ('lt_150', models.IntegerField(blank=True, default=0, null=True)),
                ('lt_100', models.IntegerField(blank=True, default=0, null=True)),
                ('lt_55', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('academic_year', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.academicyear')),
            ],
        ),
    ]
