# Generated by Django 3.2.14 on 2023-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_academicball'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
