# Generated by Django 3.2.14 on 2024-02-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20240123_2032'),
        ('category', '0007_auto_20240123_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientCategoryByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coef', models.FloatField()),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.academicyear')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'unique_together': {('category', 'academic_year')},
            },
        ),
    ]
