# Generated by Django 3.2.14 on 2026-09-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_coefficientcategorybyyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='co_author_share_percent',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='category',
            name='distribution',
            field=models.CharField(choices=[('SOLO', 'Single author'), ('FLAT_TEAM', 'Every team member gets full points'), ('WEIGHTED_SPLIT', 'Lead 100% / co-authors share %')], default='SOLO', max_length=32),
        ),
        migrations.AddField(
            model_name='category',
            name='max_co_authors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_doi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='self_submittable',
            field=models.BooleanField(default=True),
        ),
    ]
