# Generated by Django 3.2.18 on 2023-02-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20230228_1920'),
        ('user', '0002_auto_20210114_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='division/images/'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('first_name_ru', models.CharField(max_length=255, null=True)),
                ('first_name_en', models.CharField(max_length=255, null=True)),
                ('first_name_uz', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('last_name_ru', models.CharField(max_length=255, null=True)),
                ('last_name_en', models.CharField(max_length=255, null=True)),
                ('last_name_uz', models.CharField(max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/images/')),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('position_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('position_en', models.CharField(blank=True, max_length=255, null=True)),
                ('position_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Постоянный'), (2, 'Совместитель'), (3, 'Выбыл'), (4, 'почасовик')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.division')),
                ('level', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.teacherlevel')),
            ],
        ),
        migrations.CreateModel(
            name='ControlLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_limit', models.IntegerField()),
                ('high_limit', models.IntegerField()),
                ('default_ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
