# Generated by Django 3.2.14 on 2024-01-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240123_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.IntegerField(choices=[(1, 'Штатный'), (2, 'Совместитель'), (3, 'Выбыл'), (4, 'Почасовик')], default=1),
        ),
    ]
