# Generated by Django 3.2.14 on 2026-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('DEPARTMENT_REVIEWER', 'Department Reviewer'), ('SCIENTIFIC_DEPT_REVIEWER', 'Scientific Department Reviewer'), ('ADMIN', 'Administrator'), ('SYSTEM', 'System')], default='FACULTY', max_length=32),
        ),
    ]
